# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fc3b09d589633b3ad515a4dc96bb54a1e1078c54c01ce23afc3085a3c827b92c74b5a3320e82d1dfc0e837f360931a23566ec00cacf3f7ed54271138de63c79

test:
  secret_key_base: 70781fe23a523980351ad5dd43fe227eeea8fad39a811e5a299908b0f5c4d9ae4cb4cc527a2c4289a87e0cafd560bcd336a403458c86dc299ae751691c5af345

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
